apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-container
          image: alessiozubiani1996/angular-app:latest
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app
  labels:
    app: angular-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort : 80
      protocol: TCP
  selector:
    app: angular-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: angular-app
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: angular-app
          servicePort: 80
