apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  template:
    metadata:
      labels:
        run: angular-app
    spec:
      containers:
        - name: angular-container
          image: alessiozubiani1996/angular-kubernetes:latest
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app
  labels:
    run: angular-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort : 80
      protocol: TCP
      name: http
  selector:
    run: angular-app
